### PR TITLE
1726 Moving OutputMapping matching to Observed Data to Core

### LINKED ISSUE #1726: Code duplication for matching Observed Data to Outputs
Through the new feature of adding OutputMappings to Simulations, there has been created a code duplication in PK-Sim and MobI of the code mathcing the observed data to outputs according to their metaData. It si proposed for this code to be moved to Core.

### PR DESCRIPTION
**Pull request by georgeDaskalakis**
closes #1726

### CODE REVIEW

**Comment by georgeDaskalakis** [comment]
@msevestre I am converting this to a draft for now, since I want to add a few unit tests - parallelly I want to test it a bit as a user when plugged in to PK-Sim and MoBi

**Comment by msevestre** [comment]
sounds good. I can review tomorrow. Just let me know

**Comment by georgeDaskalakis** [comment]
@msevestre this is ready for review. There is a unit test that is commented out since it was quite hard for me to mock the correct resolving of the entity in the container to get a valid SimulationQuantity. I would suggest you review this and we merge in order to plugin to the solutions too and we can tackle the unit tests in a separate issue - PR.

**Review by msevestre — COMMENTED** [review]
Looks good to me. For consistency sake, I would like to be renamed to Task instead of Service. Can you do this and then merge? (Rename file, test file etc.)

**Comment by georgeDaskalakis** [comment]
> Looks good to me. For consistency sake, I would like to be renamed to Task instead of Service. Can you do this and then merge? (Rename file, test file etc.)

@msevestre  renamed. also created the issue for the unit tests. I need your approving review to merge ;)

**Comment by msevestre** [comment]
Merged

**Pull request merged**
