### PR TITLE
Fixes #2063 Calculation method formulas are not unique in MoBi projec…

### LINKED ISSUE #2063: Calculation method formulas are not unique in MoBi project after creating a brand new simulation
```
Application:
MoBi® 12.0.0

Id OBUrmqLe6UeFhtFqcV8oLQ not unique

Stack trace:

at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlCacheSerializer`3.TypedDeserialize(ICache`2 cache, XElement cacheElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedDeserialize(TBuildingBlock bb, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement simulationElement, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Serializer\MoBiSimulationXmlSerializer.cs:line 35
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, MoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 122
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, MoBiProject project, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\Xml\Services\XmlSerializationService.cs:line 94
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeContent[T](MetaDataContent content, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 165
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.addSimulationToProject(SimulationMetaData simulationMetaData, SerializationContext serializationContext) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 154
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\Mappers\ProjectMetaDataToProjectMapper.cs:line 62
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 80
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Load(IMoBiContext context) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ProjectPersistor.cs:line 56
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath) in C:\repos\OSPSuite\MoBi\src\MoBi.Core\Serialization\ORM\ContextPersistor.cs:line 93
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0() in C:\repos\OSPSuite\MoBi\src\MoBi.Presentation\Tasks\SerializationTask.cs:line 56
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

### PR DESCRIPTION
**Pull request by rwmcintosh**
…t after creating a brand new simulation

### CODE REVIEW

**Comment by msevestre** [comment]
Why are we cloning calculation methods at all? This is all read-only

**Comment by rwmcintosh** [comment]
They are cloned when you clone a SimulationConfiguration.

**Comment by msevestre** [comment]
Yeah but why??

**Comment by rwmcintosh** [comment]
Are you saying I should try this without cloning instead? Because I have no idea why - this has always been a clone.

**Comment by rwmcintosh** [comment]
It works without cloning them as well. There's a one-line change to complete in MoBi, but I'll just add that to what I'm working on now.

**Review by Yuri05 — APPROVED** [review]

**Pull request merged**
