### PR TITLE
1851 unnecessary message

### PR DESCRIPTION
**Pull request by georgeDaskalakis**

### CODE REVIEW

**Comment by georgeDaskalakis** [comment]
@msevestre @Yuri05 @PavelBal  this fixes the described issue, but would have the following side effect:

When trying to laod an empty file, simply nothing would happen. Right now, when trying to laod an empty file, the user gets notified that the file is not valid. 

For me this is not a grave issue. Of course it is possible to have both possibilities covered, but this would require more extensive code changes, and I would not suggets doing them now, at the end of the code freeze.

**Comment by Yuri05** [comment]
>When trying to laod an empty file, simply nothing would happen. 

Well, I guess when importing an empty file the user would notice it in the import configuration wizard. So fine for me.

**Comment by georgeDaskalakis** [comment]
> > When trying to laod an empty file, simply nothing would happen.
> 
> Well, I guess when importing an empty file the user would notice it in the import configuration wizard. So fine for me.

well not really....the user would just select the empty file, then nothing would happen, meaning the importer dialog would not open at all.

**Comment by rwmcintosh** [comment]
I think we should have a message for the user if there's an empty file. When they dismiss the dialog, then of course they aren't expecting a message, but in this case, they will get frustrated.

Can the file be checked earlier for empty?

**Comment by PavelBal** [comment]
"Nothing happens" is bad.

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
We'll need a specific message for this case

**Comment by georgeDaskalakis** [comment]
@msevestre this is now finalized and ready for review.

**Review by rwmcintosh — APPROVED** [review]

**Pull request merged**
